import 'package:flutter/material.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import 'package:permission_handler/permission_handler.dart';
import '../connection/connection_provider.dart';
import 'package:provider/provider.dart';

/// QR Code Scanner page for host pairing
///
/// Phase 04: Mobile App
/// Scans QR code generated by hostagent for TOFU pairing
class ScanQrPage extends StatefulWidget {
  const ScanQrPage({super.key});

  @override
  State<ScanQrPage> createState() => _ScanQrPageState();
}

class _ScanQrPageState extends State<ScanQrPage> with WidgetsBindingObserver {
  bool _hasPermission = false;
  bool _isScanning = false;
  final _controller = MobileScannerController();

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    _requestPermission();
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    _controller.dispose();
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    // Pause scanning when app is paused to save battery
    switch (state) {
      case AppLifecycleState.detached:
      case AppLifecycleState.hidden:
      case AppLifecycleState.paused:
        _controller.stop();
        break;
      case AppLifecycleState.resumed:
        _controller.start();
        break;
      case AppLifecycleState.inactive:
        break;
    }
  }

  Future<void> _requestPermission() async {
    final status = await Permission.camera.request();
    setState(() {
      _hasPermission = status.isGranted;
      if (_hasPermission) {
        _isScanning = true;
      }
    });
  }

  void _handleQrCode(String rawJson) {
    if (_isScanning == false) return;

    try {
      final connectionProvider = context.read<ConnectionProvider>();
      connectionProvider.connectWithQrString(rawJson);
      // Navigation will be handled by ConnectionProvider state change
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Invalid QR code: $e')),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Scan Host QR'),
      ),
      body: !_hasPermission
          ? _buildPermissionRequest()
          : _buildScanner(),
    );
  }

  Widget _buildPermissionRequest() {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(24.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Icon(
              Icons.camera_alt_outlined,
              size: 64,
              color: Color(0xFF6C7086),
            ),
            const SizedBox(height: 24),
            const Text(
              'Camera Permission Required',
              style: TextStyle(
                fontSize: 20,
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 16),
            const Text(
              'To pair with a host, scan the QR code displayed on the host terminal.',
              textAlign: TextAlign.center,
              style: TextStyle(
                color: Color(0xFF6C7086),
              ),
            ),
            const SizedBox(height: 32),
            ElevatedButton.icon(
              onPressed: _requestPermission,
              icon: const Icon(Icons.camera_alt),
              label: const Text('Grant Permission'),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildScanner() {
    return MobileScanner(
      controller: _controller,
      onDetect: (capture) {
        if (capture.barcodes.isNotEmpty) {
          final barcode = capture.barcodes.first;
          if (barcode.rawValue != null) {
            _handleQrCode(barcode.rawValue!);
          }
        }
      },
      overlay: _buildOverlay(),
    );
  }

  Widget _buildOverlay() {
    return SizedBox(
      width: double.infinity,
      height: double.infinity,
      child: CustomPaint(
        painter: _ScannerOverlayPainter(),
        child: const Center(),
      ),
    );
  }
}

/// Custom painter for scanner overlay
class _ScannerOverlayPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    final paint = Paint()
      ..color = const Color(0x80000000)
      ..style = PaintingStyle.fill;

    final path = Path()
      ..addRect(Rect.fromLTWH(0, 0, size.width, size.height));

    // Cut out center square for QR scanning
    final scanRegionSize = size.width * 0.7;
    final scanRegionOffset = (size.width - scanRegionSize) / 2;

    final cutout = Rect.fromLTWH(
      scanRegionOffset,
      (size.height - scanRegionSize) / 2,
      scanRegionSize,
      scanRegionSize,
    );

    path.addRect(cutout);
    path.fillType = PathFillType.evenOdd;
    canvas.drawPath(path, paint);

    // Draw border around scan region
    final borderPaint = Paint()
      ..color = const Color(0xFFCBA6F7)
      ..style = PaintingStyle.stroke
      ..strokeWidth = 2;

    canvas.drawRect(
      Rect.fromLTWH(
        scanRegionOffset,
        (size.height - scanRegionSize) / 2,
        scanRegionSize,
        scanRegionSize,
      ),
      borderPaint,
    );

    // Draw corners
    final cornerPaint = Paint()
      ..color = const Color(0xFFCBA6F7)
      ..style = PaintingStyle.stroke
      ..strokeWidth = 4
      ..strokeCap = StrokeCap.round;

    final cornerLength = scanRegionSize * 0.15;
    final left = scanRegionOffset;
    final top = (size.height - scanRegionSize) / 2;
    final right = left + scanRegionSize;
    final bottom = top + scanRegionSize;

    // Top-left
    canvas.drawLine(Offset(left, top), Offset(left + cornerLength, top), cornerPaint);
    canvas.drawLine(Offset(left, top), Offset(left, top + cornerLength), cornerPaint);

    // Top-right
    canvas.drawLine(Offset(right, top), Offset(right - cornerLength, top), cornerPaint);
    canvas.drawLine(Offset(right, top), Offset(right, top + cornerLength), cornerPaint);

    // Bottom-left
    canvas.drawLine(Offset(left, bottom), Offset(left + cornerLength, bottom), cornerPaint);
    canvas.drawLine(Offset(left, bottom), Offset(left, bottom - cornerLength), cornerPaint);

    // Bottom-right
    canvas.drawLine(Offset(right, bottom), Offset(right - cornerLength, bottom), cornerPaint);
    canvas.drawLine(Offset(right, bottom), Offset(right, bottom - cornerLength), cornerPaint);
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) => false;
}
