// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Terminal configuration for Flutter
class TerminalConfig {
  final int rows;
  final int cols;
  final String shell;

  const TerminalConfig({
    required this.rows,
    required this.cols,
    required this.shell,
  });

  static Future<TerminalConfig> default_() =>
      RustLib.instance.api.crateApiTerminalConfigDefault();

  @override
  int get hashCode => rows.hashCode ^ cols.hashCode ^ shell.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TerminalConfig &&
          runtimeType == other.runtimeType &&
          rows == other.rows &&
          cols == other.cols &&
          shell == other.shell;
}
