/// FFI helper functions for VFS and terminal events
///
/// These are convenience wrappers around the generated FFI methods.
/// Generated by flutter_rust_bridge v2.11.1.

library;

import 'third_party/mobile_bridge/frb_generated.dart';
import 'third_party/mobile_bridge/lib.dart';

// Export FFI types for convenience
export 'third_party/mobile_bridge/lib.dart'
    show DirEntry, TerminalEvent, QrPayload;
export 'third_party/mobile_bridge/frb_generated.dart' show RustLib;

// ===== DirEntry Helpers =====

/// Get directory entry name
String getDirEntryName(DirEntry entry) =>
    RustLib.instance.api.mobileBridgeApiGetDirEntryName(entry: entry);

/// Get directory entry path
String getDirEntryPath(DirEntry entry) =>
    RustLib.instance.api.mobileBridgeApiGetDirEntryPath(entry: entry);

/// Check if entry is a directory
bool isDirEntryDir(DirEntry entry) =>
    RustLib.instance.api.mobileBridgeApiIsDirEntryDir(entry: entry);

/// Check if entry is a symlink
bool isDirEntrySymlink(DirEntry entry) =>
    RustLib.instance.api.mobileBridgeApiIsDirEntrySymlink(entry: entry);

/// Get directory entry size
int? getDirEntrySize(DirEntry entry) =>
    RustLib.instance.api.mobileBridgeApiGetDirEntrySize(entry: entry)?.toInt();

/// Get directory entry modified time
int? getDirEntryModified(DirEntry entry) => RustLib.instance.api
    .mobileBridgeApiGetDirEntryModified(entry: entry)
    ?.toInt();

/// Get directory entry permissions
String? getDirEntryPermissions(DirEntry entry) =>
    RustLib.instance.api.mobileBridgeApiGetDirEntryPermissions(entry: entry);

// ===== TerminalEvent Helpers =====

/// Check if event is output
bool isEventOutput(TerminalEvent event) =>
    RustLib.instance.api.mobileBridgeApiIsEventOutput(event: event);

/// Check if event is error
bool isEventError(TerminalEvent event) =>
    RustLib.instance.api.mobileBridgeApiIsEventError(event: event);

/// Check if event is exit
bool isEventExit(TerminalEvent event) =>
    RustLib.instance.api.mobileBridgeApiIsEventExit(event: event);

/// Get event data
List<int> getEventData(TerminalEvent event) =>
    RustLib.instance.api.mobileBridgeApiGetEventData(event: event);

/// Get event error message
String getEventErrorMessage(TerminalEvent event) =>
    RustLib.instance.api.mobileBridgeApiGetEventErrorMessage(event: event);

/// Get event exit code
int getEventExitCode(TerminalEvent event) =>
    RustLib.instance.api.mobileBridgeApiGetEventExitCode(event: event);

// ===== QrPayload Helpers =====

/// Get QR IP address
String getQrIp(QrPayload payload) =>
    RustLib.instance.api.mobileBridgeApiGetQrIp(payload: payload);

/// Get QR port
int getQrPort(QrPayload payload) =>
    RustLib.instance.api.mobileBridgeApiGetQrPort(payload: payload);

/// Get QR token
String getQrToken(QrPayload payload) =>
    RustLib.instance.api.mobileBridgeApiGetQrToken(payload: payload);

/// Get QR fingerprint
String getQrFingerprint(QrPayload payload) =>
    RustLib.instance.api.mobileBridgeApiGetQrFingerprint(payload: payload);
