/// FFI helper functions for VFS and terminal events
///
/// These are convenience wrappers around the generated FFI methods.
/// Generated by flutter_rust_bridge v2.11.1.
///
/// Note: Most helper functions are now available directly from api.dart
/// This file provides compatibility layer with positional parameters.

library;

import 'api.dart' show DirEntry, TerminalEvent, QrPayload;
import 'api.dart' as frb_api;

// Export FFI types for convenience
export 'api.dart' show DirEntry, TerminalEvent, QrPayload;
export 'frb_generated.dart' show RustLib;

// ===== DirEntry Helpers =====

/// Get directory entry name
String getDirEntryName(DirEntry entry) => frb_api.getDirEntryName(entry: entry);

/// Get directory entry path
String getDirEntryPath(DirEntry entry) => frb_api.getDirEntryPath(entry: entry);

/// Check if entry is a directory
bool isDirEntryDir(DirEntry entry) => frb_api.isDirEntryDir(entry: entry);

/// Check if entry is a symlink
bool isDirEntrySymlink(DirEntry entry) =>
    frb_api.isDirEntrySymlink(entry: entry);

/// Get directory entry size
int? getDirEntrySize(DirEntry entry) =>
    frb_api.getDirEntrySize(entry: entry)?.toInt();

/// Get directory entry modified time
int? getDirEntryModified(DirEntry entry) =>
    frb_api.getDirEntryModified(entry: entry)?.toInt();

/// Get directory entry permissions
String? getDirEntryPermissions(DirEntry entry) =>
    frb_api.getDirEntryPermissions(entry: entry);

// ===== TerminalEvent Helpers =====

/// Check if event is output
bool isEventOutput(TerminalEvent event) => frb_api.isEventOutput(event: event);

/// Check if event is error
bool isEventError(TerminalEvent event) => frb_api.isEventError(event: event);

/// Check if event is exit
bool isEventExit(TerminalEvent event) => frb_api.isEventExit(event: event);

/// Get event data
List<int> getEventData(TerminalEvent event) =>
    frb_api.getEventData(event: event);

/// Get event error message
String getEventErrorMessage(TerminalEvent event) =>
    frb_api.getEventErrorMessage(event: event);

/// Get event exit code
int getEventExitCode(TerminalEvent event) =>
    frb_api.getEventExitCode(event: event);

// ===== QrPayload Helpers =====

/// Get QR IP address
String getQrIp(QrPayload payload) => frb_api.getQrIp(payload: payload);

/// Get QR port
int getQrPort(QrPayload payload) => frb_api.getQrPort(payload: payload);

/// Get QR token
String getQrToken(QrPayload payload) => frb_api.getQrToken(payload: payload);

/// Get QR fingerprint
String getQrFingerprint(QrPayload payload) =>
    frb_api.getQrFingerprint(payload: payload);
