// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_DirEntryPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDirEntry;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_QrPayloadPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQrPayload;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_TerminalCommandPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalCommand;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_TerminalEventPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEvent;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  DirEntry
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDirEntry(
    dynamic raw,
  );

  @protected
  QrPayload
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQrPayload(
    dynamic raw,
  );

  @protected
  TerminalCommand
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalCommand(
    dynamic raw,
  );

  @protected
  TerminalEvent
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEvent(
    dynamic raw,
  );

  @protected
  DirEntry
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDirEntry(
    dynamic raw,
  );

  @protected
  QrPayload
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQrPayload(
    dynamic raw,
  );

  @protected
  TerminalCommand
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalCommand(
    dynamic raw,
  );

  @protected
  TerminalEvent
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEvent(
    dynamic raw,
  );

  @protected
  DirEntry
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDirEntry(
    dynamic raw,
  );

  @protected
  QrPayload
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQrPayload(
    dynamic raw,
  );

  @protected
  TerminalCommand
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalCommand(
    dynamic raw,
  );

  @protected
  TerminalEvent
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEvent(
    dynamic raw,
  );

  @protected
  RustStreamSink<List<DirEntry>>
  dco_decode_StreamSink_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDirEntry_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  FileContentData dco_decode_box_autoadd_file_content_data(dynamic raw);

  @protected
  FileWatcherEventData dco_decode_box_autoadd_file_watcher_event_data(
    dynamic raw,
  );

  @protected
  (int, List<DirEntry>, bool)
  dco_decode_box_autoadd_record_u_32_list_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_dir_entry_bool(
    dynamic raw,
  );

  @protected
  SessionCommand dco_decode_box_autoadd_session_command(dynamic raw);

  @protected
  SessionHistoryData dco_decode_box_autoadd_session_history_data(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  VibeInput dco_decode_box_autoadd_vibe_input(dynamic raw);

  @protected
  FileContentData dco_decode_file_content_data(dynamic raw);

  @protected
  FileWatcherEventData dco_decode_file_watcher_event_data(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<DirEntry>
  dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDirEntry(
    dynamic raw,
  );

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SessionData> dco_decode_list_session_data(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  FileContentData? dco_decode_opt_box_autoadd_file_content_data(dynamic raw);

  @protected
  FileWatcherEventData? dco_decode_opt_box_autoadd_file_watcher_event_data(
    dynamic raw,
  );

  @protected
  (int, List<DirEntry>, bool)?
  dco_decode_opt_box_autoadd_record_u_32_list_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_dir_entry_bool(
    dynamic raw,
  );

  @protected
  SessionHistoryData? dco_decode_opt_box_autoadd_session_history_data(
    dynamic raw,
  );

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  (int, List<DirEntry>, bool)
  dco_decode_record_u_32_list_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_dir_entry_bool(
    dynamic raw,
  );

  @protected
  SessionCommand dco_decode_session_command(dynamic raw);

  @protected
  SessionData dco_decode_session_data(dynamic raw);

  @protected
  SessionHistoryData dco_decode_session_history_data(dynamic raw);

  @protected
  TerminalConfig dco_decode_terminal_config(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VibeInput dco_decode_vibe_input(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  DirEntry
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDirEntry(
    SseDeserializer deserializer,
  );

  @protected
  QrPayload
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQrPayload(
    SseDeserializer deserializer,
  );

  @protected
  TerminalCommand
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalCommand(
    SseDeserializer deserializer,
  );

  @protected
  TerminalEvent
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEvent(
    SseDeserializer deserializer,
  );

  @protected
  DirEntry
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDirEntry(
    SseDeserializer deserializer,
  );

  @protected
  QrPayload
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQrPayload(
    SseDeserializer deserializer,
  );

  @protected
  TerminalCommand
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalCommand(
    SseDeserializer deserializer,
  );

  @protected
  TerminalEvent
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEvent(
    SseDeserializer deserializer,
  );

  @protected
  DirEntry
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDirEntry(
    SseDeserializer deserializer,
  );

  @protected
  QrPayload
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQrPayload(
    SseDeserializer deserializer,
  );

  @protected
  TerminalCommand
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalCommand(
    SseDeserializer deserializer,
  );

  @protected
  TerminalEvent
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEvent(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<List<DirEntry>>
  sse_decode_StreamSink_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDirEntry_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  FileContentData sse_decode_box_autoadd_file_content_data(
    SseDeserializer deserializer,
  );

  @protected
  FileWatcherEventData sse_decode_box_autoadd_file_watcher_event_data(
    SseDeserializer deserializer,
  );

  @protected
  (int, List<DirEntry>, bool)
  sse_decode_box_autoadd_record_u_32_list_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_dir_entry_bool(
    SseDeserializer deserializer,
  );

  @protected
  SessionCommand sse_decode_box_autoadd_session_command(
    SseDeserializer deserializer,
  );

  @protected
  SessionHistoryData sse_decode_box_autoadd_session_history_data(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  VibeInput sse_decode_box_autoadd_vibe_input(SseDeserializer deserializer);

  @protected
  FileContentData sse_decode_file_content_data(SseDeserializer deserializer);

  @protected
  FileWatcherEventData sse_decode_file_watcher_event_data(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<DirEntry>
  sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDirEntry(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SessionData> sse_decode_list_session_data(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  FileContentData? sse_decode_opt_box_autoadd_file_content_data(
    SseDeserializer deserializer,
  );

  @protected
  FileWatcherEventData? sse_decode_opt_box_autoadd_file_watcher_event_data(
    SseDeserializer deserializer,
  );

  @protected
  (int, List<DirEntry>, bool)?
  sse_decode_opt_box_autoadd_record_u_32_list_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_dir_entry_bool(
    SseDeserializer deserializer,
  );

  @protected
  SessionHistoryData? sse_decode_opt_box_autoadd_session_history_data(
    SseDeserializer deserializer,
  );

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  (int, List<DirEntry>, bool)
  sse_decode_record_u_32_list_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_dir_entry_bool(
    SseDeserializer deserializer,
  );

  @protected
  SessionCommand sse_decode_session_command(SseDeserializer deserializer);

  @protected
  SessionData sse_decode_session_data(SseDeserializer deserializer);

  @protected
  SessionHistoryData sse_decode_session_history_data(
    SseDeserializer deserializer,
  );

  @protected
  TerminalConfig sse_decode_terminal_config(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VibeInput sse_decode_vibe_input(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDirEntry(
    DirEntry self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQrPayload(
    QrPayload self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalCommand(
    TerminalCommand self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEvent(
    TerminalEvent self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDirEntry(
    DirEntry self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQrPayload(
    QrPayload self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalCommand(
    TerminalCommand self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEvent(
    TerminalEvent self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDirEntry(
    DirEntry self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQrPayload(
    QrPayload self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalCommand(
    TerminalCommand self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEvent(
    TerminalEvent self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_StreamSink_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDirEntry_Sse(
    RustStreamSink<List<DirEntry>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_file_content_data(
    FileContentData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_file_watcher_event_data(
    FileWatcherEventData self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_box_autoadd_record_u_32_list_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_dir_entry_bool(
    (int, List<DirEntry>, bool) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_session_command(
    SessionCommand self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_session_history_data(
    SessionHistoryData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_vibe_input(
    VibeInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_file_content_data(
    FileContentData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_file_watcher_event_data(
    FileWatcherEventData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void
  sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDirEntry(
    List<DirEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_session_data(
    List<SessionData> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_file_content_data(
    FileContentData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_file_watcher_event_data(
    FileWatcherEventData? self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_opt_box_autoadd_record_u_32_list_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_dir_entry_bool(
    (int, List<DirEntry>, bool)? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_session_history_data(
    SessionHistoryData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void
  sse_encode_record_u_32_list_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_dir_entry_bool(
    (int, List<DirEntry>, bool) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_command(
    SessionCommand self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_data(SessionData self, SseSerializer serializer);

  @protected
  void sse_encode_session_history_data(
    SessionHistoryData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_terminal_config(
    TerminalConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_vibe_input(VibeInput self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDirEntry(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDirEntry(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDirEntry(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDirEntry(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQrPayload(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQrPayload(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQrPayload(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQrPayload(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalCommand(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalCommand(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalCommand(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalCommand(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEvent(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEvent(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEvent(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEvent(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDirEntry(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDirEntry(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQrPayload(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQrPayload(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalCommand(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalCommand(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEvent(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTerminalEvent(
    int ptr,
  );
}
